# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: swiftlang/swift:nightly-jammy
    steps:
    - uses: actions/checkout@v4
    - name: Build standard library
      run: swift run talk compile module Library/Standard
    - name: Run tests
      run: swift test -v
